 SELECT 
       ID AS LISTING_ID
       , LISTING_URL
       , INITCAP(NAME) AS NAME
       , UPPER(ROOM_TYPE) AS ROOM_TYPE
       , MINIMUM_NIGHTS
       , HOST_ID
       , REPLACE(PRICE,'$')::INT AS PRICE
       , CREATED_AT
       , UPDATED_AT
    FROM AIRBNB.RAW.RAW_LISTINGS