SELECT
        LISTING_ID
        , DATE::DATE AS DATE
        , UPPER(REVIEWER_NAME) AS REVIEWER_NAME 
        , INITCAP(COMMENTS) AS COMMENTS
        , UPPER(SENTIMENT) AS SENTIMENT
    FROM AIRBNB.RAW.RAW_REVIEWS